import { Router, type IRouter } from "express";
import { authMiddleware, verifyWeddingAccess } from "../lib/auth";
import healthRouter from "./health";
import authRouter from "./auth";
import weddingsRouter from "./weddings";
import guestsRouter from "./guests";
import giftsRouter from "./gifts";
import tasksRouter from "./tasks";
import vendorsRouter from "./vendors";
import coordinatorsRouter from "./coordinators";
import scheduleRouter from "./schedule";
import budgetRouter from "./budget";
import seatingRouter from "./seating";
import messagesRouter from "./messages";
import settingsRouter from "./settings";
import dashboardRouter from "./dashboard";
import webhooksRouter from "./webhooks";
import invitationsRouter from "./invitations";
import remindersRouter from "./reminders";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(weddingsRouter);
router.use("/weddings/:weddingId", authMiddleware, verifyWeddingAccess);
router.use(guestsRouter);
router.use(giftsRouter);
router.use(tasksRouter);
router.use(vendorsRouter);
router.use(coordinatorsRouter);
router.use(scheduleRouter);
router.use(budgetRouter);
router.use(seatingRouter);
router.use(messagesRouter);
router.use(settingsRouter);
router.use(dashboardRouter);
router.use(webhooksRouter);
router.use(invitationsRouter);
router.use(remindersRouter);

export default router;
